#!/usr/bin/env bash
set -e
lb config noauto \
  --mode ubuntu \
  --distribution noble \
  --architectures amd64 \
  --linux-flavours amd64 \
  --binary-images iso-hybrid \
  --bootloaders "grub-efi grub-pc" \
  --archive-areas "main restricted universe multiverse" \
  --firmware-binary true \
  --firmware-chroot true \
  --apt-recommends true \
  --debian-installer live \
  --bootappend-live "boot=live components quiet splash username=meuser hostname=me10-pc"
